package com.necohorne.gymapp.Models;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;

@Entity(tableName = "program")
public class Program implements Parcelable {

    @PrimaryKey(autoGenerate = true) //this variable is auto generated by Room for the DB and will not be found in the JSON data.
    private int primaryKey;
    private String day;
    private ArrayList<MuscleSet> sets;

    @Ignore //this annotation is only to let Room know not to use this constructor.
    public Program() {
    }

    public Program(int primaryKey, String day, ArrayList<MuscleSet> sets) {
        this.primaryKey = primaryKey;
        this.day = day;
        this.sets = sets;
    }

    //Constructor and methods needed for Parcelable
    protected Program(Parcel in) {
        primaryKey = in.readInt();
        day = in.readString();
        this.sets = in.readArrayList(getClass().getClassLoader());
    }

    public static final Creator<Program> CREATOR = new Creator<Program>() {
        @Override
        public Program createFromParcel(Parcel in) {
            return new Program(in);
        }

        @Override
        public Program[] newArray(int size) {
            return new Program[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(primaryKey);
        dest.writeString(day);
        dest.writeList(sets);
    }

    //Getters and Setters
    public int getPrimaryKey() {
        return primaryKey;
    }

    public void setPrimaryKey(int primaryKey) {
        this.primaryKey = primaryKey;
    }

    public String getDay() {
        return day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public ArrayList<MuscleSet> getSets() {
        return sets;
    }

    public void setSets(ArrayList<MuscleSet> sets) {
        this.sets = sets;
    }

    //Other Class Methods
    @Override
    public String toString() {
        return "Program{" +
                "primaryKey=" + primaryKey +
                ", mDay='" + day + '\'' +
                ", sets=" + sets +
                '}';
    }
}
